version: "3.9"

services:
  tp-framework-test:
    build:
      context: .
      dockerfile: './Dockerfile'
      args:
        REQUIREMENTS_FILE: "requirements-dev.txt"
    volumes:
      - ./out:/tp-framework/out
      - ./qualitytests:/tp-framework/qualitytests
    entrypoint: pytest