version: "3.9"

services:

  codeql_v2_9_2:
    image: tpf_codeql_v2_9_2
    build:
      context: './SAST/codeql/codeql_v2_9_2'
      dockerfile: "./Dockerfile"
    volumes:
      - codeql_v2_9_2:/codeql
      - codeql_interface_v2_9_2:/tp-framework/SAST/codeql/codeql_v2_9_2
  
  codeql_v2_13_1:
    image: tpf_codeql_v2_13_1
    build:
      context: './SAST/codeql/codeql_v2_13_1'
      dockerfile: "./Dockerfile"
    volumes:
      - codeql_v2_13_1:/codeql
      - codeql_interface_v2_13_1:/tp-framework/SAST/codeql/codeql_v2_13_1

  tp-framework-dev:
    image: tp-framework-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements-dev.txt"
      dockerfile: "./Dockerfile"
    env_file:
      - ./.env
    volumes:
      - codeql_v2_9_2:/codeql_v2_9_2
      - codeql_interface_v2_9_2:/tp-framework/SAST/codeql/codeql_v2_9_2
      - codeql_v2_13_1:/codeql_v2_13_1
      - codeql_interface_v2_13_1:/tp-framework/SAST/codeql/codeql_v2_13_1
      - ./testability_patterns:/tp-framework/testability_patterns
      - ./out:/tp-framework/out
      - ./in:/tp-framework/in
      - ./SAST:/SAST
      - ./tp_framework:/tp-framework/tp_framework
      - ./discovery:/tp-framework/discovery
      - ./qualitytests:/tp-framework/qualitytests
    entrypoint: bash

volumes:
  codeql_v2_9_2:
  codeql_interface_v2_9_2:
  codeql_v2_13_1:
  codeql_interface_v2_13_1: